import { type NormalisedAid } from './subvention-sources.ts';

// Hand-curated national schemes with their official application entry point.
// Deliberately factual and short — the ranker and the AI reader use these
// fields verbatim. Never invent a scheme, never invent an amount.
export const CURATED_AIDS: Omit<
  NormalisedAid,
  'sourceKey' | 'searchText' | 'contentHash'
>[] = [
  {
    source: 'CURATED',
    sourceId: 'fdva-2',
    title:
      "FDVA 2 — Fonctionnement et innovation (Fonds pour le développement de la vie associative)",
    description:
      "Soutien au fonctionnement global ou aux projets innovants des associations, quel que soit leur secteur. Instruit chaque année au niveau départemental ou régional via Le Compte Asso. Montant courant : 1 000 à 15 000 €.",
    eligibility:
      "Association loi 1901 déclarée depuis au moins un an, avec un numéro RNA et un SIRET, hors associations sportives affiliées à une fédération agréée (voir Agence nationale du Sport).",
    financers: ['État — Ministère chargé de la Vie associative'],
    instructors: ['DRAJES', 'DDETS'],
    programs: ['FDVA'],
    audiences: ['ASSOCIATION'],
    aidTypes: ['Subvention'],
    categories: ['Vie associative', 'Fonctionnement'],
    perimeterScale: 'NATIONAL',
    perimeter: 'France',
    isCallForProject: false,
    url: 'https://www.associations.gouv.fr/FDVA.html',
    applicationUrl: 'https://lecompteasso.associations.gouv.fr/',
    recurrence: 'Annuelle',
    isEuropean: false,
    isLive: true,
  },
  {
    source: 'CURATED',
    sourceId: 'fonjep',
    title:
      "Poste FONJEP — Fonds de coopération de la jeunesse et de l'éducation populaire",
    description:
      "Cofinancement pluriannuel d'un poste salarié permanent (environ 7 000 € par an pendant 3 ans, renouvelable) dans une association d'éducation populaire, de jeunesse, de cohésion sociale ou d'insertion.",
    eligibility:
      "Association employeuse, projet associatif structuré, demande déposée auprès des services déconcentrés de l'État (DRAJES / DDETS).",
    financers: ['État', 'FONJEP'],
    instructors: ['DRAJES', 'DDETS'],
    programs: ['FONJEP'],
    audiences: ['ASSOCIATION'],
    aidTypes: ['Subvention', "Aide à l'emploi"],
    categories: ['Emploi', 'Jeunesse', 'Éducation populaire'],
    perimeterScale: 'NATIONAL',
    perimeter: 'France',
    isCallForProject: false,
    url: 'https://www.fonjep.org/',
    applicationUrl: 'https://lecompteasso.associations.gouv.fr/',
    recurrence: 'Annuelle',
    isEuropean: false,
    isLive: true,
  },
  {
    source: 'CURATED',
    sourceId: 'ans-psf',
    title: 'Agence nationale du Sport — Projet Sportif Fédéral (PSF)',
    description:
      "Subventions de fonctionnement et de projet pour les clubs et comités affiliés, instruites par leur fédération au titre de la part territoriale. Inclut l'emploi sportif et l'Aisance aquatique.",
    eligibility:
      "Association sportive affiliée à une fédération agréée, à jour de ses obligations déclaratives.",
    financers: ['Agence nationale du Sport'],
    instructors: ['Fédérations sportives agréées'],
    programs: ['PSF'],
    audiences: ['ASSOCIATION'],
    aidTypes: ['Subvention'],
    categories: ['Sport'],
    perimeterScale: 'NATIONAL',
    perimeter: 'France',
    isCallForProject: false,
    url: 'https://www.agencedusport.fr/',
    applicationUrl: 'https://lecompteasso.associations.gouv.fr/',
    recurrence: 'Annuelle',
    isEuropean: false,
    isLive: true,
  },
  {
    source: 'CURATED',
    sourceId: 'crous-culture-actions',
    title: 'CROUS — Culture-ActionS (projets étudiants)',
    description:
      "Financement de projets portés par des étudiants ou des associations étudiantes : culture, solidarité, sport, environnement, engagement citoyen. Plusieurs commissions par an.",
    eligibility:
      "Étudiant inscrit dans un établissement d'enseignement supérieur ou association étudiante.",
    financers: ['CNOUS', 'CROUS'],
    instructors: ['CROUS'],
    programs: ['Culture-ActionS'],
    audiences: ['ASSOCIATION', 'PARTICULIER'],
    aidTypes: ['Subvention'],
    categories: ['Culture', 'Vie étudiante', 'Engagement'],
    perimeterScale: 'NATIONAL',
    perimeter: 'France',
    isCallForProject: false,
    url: 'https://www.etudiant.gouv.fr/fr/culture-actions-1370',
    applicationUrl: 'https://www.messervices.etudiant.gouv.fr/',
    recurrence: 'Plusieurs commissions par an',
    isEuropean: false,
    isLive: true,
  },
  {
    source: 'CURATED',
    sourceId: 'fse-plus',
    title: 'FSE+ — Fonds social européen plus',
    description:
      "Cofinancement européen (souvent 40 à 60 %) de projets d'insertion professionnelle, de formation, de lutte contre la pauvreté et d'inclusion. Appels à projets régionaux et nationaux via Ma Démarche FSE+.",
    eligibility:
      "Structure porteuse d'un projet d'inclusion, d'emploi ou de formation, capable d'avancer la trésorerie et de tenir une comptabilité analytique.",
    financers: ['Union européenne', 'État'],
    instructors: ['DREETS', 'Conseils régionaux'],
    programs: ['FSE+'],
    audiences: ['ASSOCIATION', 'ENTREPRISE', 'COLLECTIVITE'],
    aidTypes: ['Subvention'],
    categories: ['Emploi', 'Insertion', 'Formation'],
    perimeterScale: 'EUROPEEN',
    perimeter: 'Union européenne',
    isCallForProject: true,
    url: 'https://www.fse.gouv.fr/',
    applicationUrl: 'https://ma-demarche-fse.fr/',
    isEuropean: true,
    isLive: true,
  },
  {
    source: 'CURATED',
    sourceId: 'erasmus-plus-jeunesse',
    title: 'Erasmus+ — Jeunesse et Sport',
    description:
      "Financement de mobilités, d'échanges de jeunes, de partenariats de coopération et de projets de participation des jeunes. Forfaits européens (frais de voyage et coûts organisationnels).",
    eligibility:
      "Association, collectivité ou organisme actif dans le champ de la jeunesse ou du sport.",
    financers: ['Union européenne', 'Agence Erasmus+ France Jeunesse & Sport'],
    instructors: ['Agence Erasmus+ France Jeunesse & Sport'],
    programs: ['Erasmus+'],
    audiences: ['ASSOCIATION', 'COLLECTIVITE'],
    aidTypes: ['Subvention'],
    categories: ['Jeunesse', 'Mobilité', 'Sport'],
    perimeterScale: 'EUROPEEN',
    perimeter: 'Union européenne',
    isCallForProject: true,
    url: 'https://www.erasmusplus-jeunesse.fr/',
    applicationUrl: 'https://www.erasmusplus-jeunesse.fr/deposer-un-projet',
    recurrence: '3 à 4 dates limites par an',
    isEuropean: true,
    isLive: true,
  },
  {
    source: 'CURATED',
    sourceId: 'service-civique-agrement',
    title: 'Service Civique — Agrément et prise en charge des volontaires',
    description:
      "L'État prend en charge l'indemnité du volontaire et sa protection sociale ; la structure verse une prestation complémentaire mensuelle. Levier RH majeur pour une petite structure.",
    eligibility:
      "Association, collectivité ou établissement public agréé par l'Agence du Service Civique.",
    financers: ['Agence du Service Civique'],
    instructors: ['Agence du Service Civique'],
    programs: ['Service Civique'],
    audiences: ['ASSOCIATION', 'COLLECTIVITE'],
    aidTypes: ["Aide à l'emploi"],
    categories: ['Emploi', 'Jeunesse', 'Engagement'],
    perimeterScale: 'NATIONAL',
    perimeter: 'France',
    isCallForProject: false,
    url: 'https://www.service-civique.gouv.fr/',
    applicationUrl: 'https://www.service-civique.gouv.fr/organismes',
    recurrence: 'En continu',
    isEuropean: false,
    isLive: true,
  },
  {
    source: 'CURATED',
    sourceId: 'ademe-appels-projets',
    title: 'ADEME — Aides à la transition écologique et appels à projets',
    description:
      "Diagnostics, études, investissements et animation sur l'énergie, les déchets, l'économie circulaire, la mobilité et l'alimentation durable. Taux d'aide fréquents : 30 à 70 % selon la nature et la taille de la structure.",
    eligibility:
      'Association, entreprise ou collectivité portant un projet de transition écologique.',
    financers: ['ADEME'],
    instructors: ['ADEME'],
    programs: ['Agir pour la transition'],
    audiences: ['ASSOCIATION', 'ENTREPRISE', 'COLLECTIVITE'],
    aidTypes: ['Subvention', 'Ingénierie'],
    categories: ['Environnement', 'Énergie', 'Économie circulaire'],
    perimeterScale: 'NATIONAL',
    perimeter: 'France',
    isCallForProject: true,
    url: 'https://agirpourlatransition.ademe.fr/entreprises/aides-financieres',
    applicationUrl:
      'https://agirpourlatransition.ademe.fr/entreprises/aides-financieres',
    isEuropean: false,
    isLive: true,
  },
  {
    source: 'CURATED',
    sourceId: 'bpifrance-aides',
    title: "Bpifrance — Subventions, avances récupérables et prêts d'amorçage",
    description:
      "Financement de l'innovation et de la croissance : Bourse French Tech, aide au développement deep tech, prêt d'amorçage, diagnostics. Cumulable avec le CIR.",
    eligibility:
      "PME ou startup immatriculée en France, projet d'innovation caractérisé.",
    financers: ['Bpifrance'],
    instructors: ['Bpifrance'],
    programs: ['French Tech'],
    audiences: ['ENTREPRISE'],
    aidTypes: ['Subvention', 'Avance récupérable', 'Prêt'],
    categories: ['Innovation', "Création d'entreprise"],
    perimeterScale: 'NATIONAL',
    perimeter: 'France',
    isCallForProject: false,
    url: 'https://www.bpifrance.fr/catalogue-offres',
    applicationUrl: 'https://mon.bpifrance.fr/',
    isEuropean: false,
    isLive: true,
  },
  {
    source: 'CURATED',
    sourceId: 'cir-cii',
    title: "CIR / CII — Crédit d'impôt recherche et innovation",
    description:
      "30 % des dépenses de R&D éligibles (CIR) et 20 % des dépenses de conception de prototypes ou d'installations pilotes pour les PME (CII). Remboursable immédiatement pour les PME.",
    eligibility:
      "Entreprise soumise à l'IS ou à l'IR engageant des dépenses de R&D ou d'innovation en France.",
    financers: ['État — Direction générale des Finances publiques'],
    instructors: ['DGFiP', 'MESR'],
    programs: ['CIR', 'CII'],
    audiences: ['ENTREPRISE'],
    aidTypes: ["Crédit d'impôt"],
    categories: ['Innovation', 'Recherche', 'Fiscalité'],
    perimeterScale: 'NATIONAL',
    perimeter: 'France',
    isCallForProject: false,
    url: 'https://www.entreprises.gouv.fr/fr/innovation/credit-d-impot-recherche',
    applicationUrl: 'https://www.impots.gouv.fr/',
    recurrence: 'Annuelle, avec la liasse fiscale',
    isEuropean: false,
    isLive: true,
  },
  {
    source: 'CURATED',
    sourceId: 'jei',
    title: 'JEI — Statut Jeune Entreprise Innovante',
    description:
      "Exonérations de cotisations patronales sur les personnels de R&D et allégements fiscaux locaux pour les entreprises de moins de 8 ans consacrant au moins 15 % de leurs charges à la R&D.",
    eligibility:
      'PME de moins de 8 ans, indépendante, avec au moins 15 % de dépenses de R&D.',
    financers: ['État', 'URSSAF'],
    instructors: ['URSSAF'],
    programs: ['JEI'],
    audiences: ['ENTREPRISE'],
    aidTypes: ['Exonération'],
    categories: ['Innovation', "Création d'entreprise"],
    perimeterScale: 'NATIONAL',
    perimeter: 'France',
    isCallForProject: false,
    url: 'https://entreprendre.service-public.fr/vosdroits/F31188',
    isEuropean: false,
    isLive: true,
  },
  {
    source: 'CURATED',
    sourceId: 'fdva-1-formation',
    title: 'FDVA 1 — Formation des bénévoles',
    description:
      "Financement de plans de formation des bénévoles élus ou responsables d'activité. Instruit au niveau régional, dépôt sur Le Compte Asso.",
    eligibility:
      "Association loi 1901 employant peu ou pas de salariés, avec un projet de formation de ses bénévoles.",
    financers: ['État — Ministère chargé de la Vie associative'],
    instructors: ['DRAJES'],
    programs: ['FDVA'],
    audiences: ['ASSOCIATION'],
    aidTypes: ['Subvention'],
    categories: ['Formation', 'Vie associative'],
    perimeterScale: 'NATIONAL',
    perimeter: 'France',
    isCallForProject: false,
    url: 'https://www.associations.gouv.fr/FDVA.html',
    applicationUrl: 'https://lecompteasso.associations.gouv.fr/',
    recurrence: 'Annuelle',
    isEuropean: false,
    isLive: true,
  },
  {
    source: 'CURATED',
    sourceId: 'politique-de-la-ville',
    title: 'Contrat de ville — Appels à projets Politique de la ville',
    description:
      "Financement d'actions dans les quartiers prioritaires (QPV) : éducation, emploi, santé, culture, lien social. Instruit conjointement par l'État et les collectivités signataires du contrat de ville.",
    eligibility:
      "Association intervenant sur un quartier prioritaire de la politique de la ville.",
    financers: ['État — ANCT', 'Collectivités signataires'],
    instructors: ['Préfectures', 'Délégués du préfet'],
    programs: ['Contrat de ville'],
    audiences: ['ASSOCIATION', 'COLLECTIVITE'],
    aidTypes: ['Subvention'],
    categories: ['Cohésion sociale', 'Éducation', 'Quartiers prioritaires'],
    perimeterScale: 'NATIONAL',
    perimeter: 'France',
    isCallForProject: true,
    url: 'https://agence-cohesion-territoires.gouv.fr/',
    applicationUrl: 'https://lecompteasso.associations.gouv.fr/',
    recurrence: 'Annuelle',
    isEuropean: false,
    isLive: true,
  },
  {
    source: 'CURATED',
    sourceId: 'fonds-de-dotation-mecenat',
    title: "Mécénat d'entreprise — Réduction d'impôt (art. 238 bis)",
    description:
      "Une entreprise mécène bénéficie de 60 % de réduction d'impôt sur ses dons (40 % au-delà de 2 M€), dans la limite de 20 000 € ou 0,5 % du chiffre d'affaires. Levier direct pour financer un projet associatif par des partenaires privés.",
    eligibility:
      "Organisme d'intérêt général habilité à délivrer des reçus fiscaux (art. 200 / 238 bis du CGI).",
    financers: ['Entreprises mécènes'],
    instructors: ['DGFiP'],
    programs: ['Mécénat'],
    audiences: ['ASSOCIATION'],
    aidTypes: ['Mécénat'],
    categories: ['Mécénat', 'Fiscalité'],
    perimeterScale: 'NATIONAL',
    perimeter: 'France',
    isCallForProject: false,
    url: 'https://www.economie.gouv.fr/entreprises/mecenat-entreprise',
    isEuropean: false,
    isLive: true,
  },
];
