import {
  defineObject,
  FieldType,
  OnDeleteAction,
  STANDARD_OBJECT_UNIVERSAL_IDENTIFIERS,
} from 'twenty-sdk/define';

import {
  invoiceStatusOptions,
  INVOICE_STATUS,
  manyToOne,
  oneToMany,
  recurrenceOptions,
  TAX_MODE,
  taxModeOptions,
} from '../constants/field-vocabulary.ts';
import {
  LABEL_IDENTIFIER_IDS,
  OBJECT_IDS,
  RELATION_IDS,
} from '../constants/universal-identifiers.ts';

export default defineObject({
  universalIdentifier: OBJECT_IDS.invoice,
  nameSingular: 'invoice',
  namePlural: 'invoices',
  labelSingular: 'Facture',
  labelPlural: 'Factures',
  description:
    'Facture de vente : lignes, TVA par ligne, échéance, encaissements et relances.',
  icon: 'IconFileInvoice',
  labelIdentifierFieldMetadataUniversalIdentifier:
    LABEL_IDENTIFIER_IDS.invoiceNumber,
  fields: [
    {
      universalIdentifier: LABEL_IDENTIFIER_IDS.invoiceNumber,
      type: FieldType.TEXT,
      name: 'number',
      label: 'Numéro',
      description:
        'Numéro séquentiel sans rupture, exigence de l’article L102 B du LPF',
      icon: 'IconHash',
      defaultValue: "''",
    },
    {
      universalIdentifier: 'b11a0100-0001-4000-8000-000000000002',
      type: FieldType.SELECT,
      name: 'status',
      label: 'Statut',
      icon: 'IconProgress',
      defaultValue: `'${INVOICE_STATUS.DRAFT}'`,
      options: invoiceStatusOptions,
    },
    {
      universalIdentifier: 'b11a0100-0001-4000-8000-000000000003',
      type: FieldType.TEXT,
      name: 'clientName',
      label: 'Nom du client',
      description:
        "Copie du nom à l'émission : une facture ne change jamais, même si la fiche client évolue.",
      icon: 'IconUser',
      isNullable: true,
    },
    {
      universalIdentifier: 'b11a0100-0001-4000-8000-000000000004',
      type: FieldType.EMAILS,
      name: 'clientEmails',
      label: 'Courriels du client',
      icon: 'IconMail',
      isNullable: true,
    },
    {
      universalIdentifier: 'b11a0100-0001-4000-8000-000000000005',
      type: FieldType.ADDRESS,
      name: 'clientAddress',
      label: 'Adresse de facturation',
      icon: 'IconMapPin',
      isNullable: true,
    },
    {
      universalIdentifier: 'b11a0100-0001-4000-8000-000000000006',
      type: FieldType.DATE_TIME,
      name: 'issueDate',
      label: "Date d'émission",
      icon: 'IconCalendar',
      isNullable: true,
    },
    {
      universalIdentifier: 'b11a0100-0001-4000-8000-000000000007',
      type: FieldType.DATE_TIME,
      name: 'dueDate',
      label: "Date d'échéance",
      icon: 'IconCalendarDue',
      isNullable: true,
    },
    {
      universalIdentifier: 'b11a0100-0001-4000-8000-000000000008',
      type: FieldType.DATE_TIME,
      name: 'paidDate',
      label: 'Date de paiement',
      icon: 'IconCalendarCheck',
      isNullable: true,
    },
    {
      universalIdentifier: 'b11a0100-0001-4000-8000-000000000009',
      type: FieldType.SELECT,
      name: 'taxMode',
      label: 'Régime de TVA',
      icon: 'IconReceiptTax',
      defaultValue: `'${TAX_MODE.EXCLUSIVE}'`,
      options: taxModeOptions('01'),
    },
    {
      universalIdentifier: 'b11a0100-0001-4000-8000-00000000000a',
      type: FieldType.CURRENCY,
      name: 'amountSubtotal',
      label: 'Total HT',
      icon: 'IconCurrencyEuro',
      isNullable: true,
    },
    {
      universalIdentifier: 'b11a0100-0001-4000-8000-00000000000b',
      type: FieldType.CURRENCY,
      name: 'amountTax',
      label: 'TVA',
      icon: 'IconPercentage',
      isNullable: true,
    },
    {
      universalIdentifier: 'b11a0100-0001-4000-8000-00000000000c',
      type: FieldType.CURRENCY,
      name: 'amountTotal',
      label: 'Total TTC',
      icon: 'IconCurrencyEuro',
      isNullable: true,
    },
    {
      universalIdentifier: 'b11a0100-0001-4000-8000-00000000000d',
      type: FieldType.CURRENCY,
      name: 'amountPaid',
      label: 'Montant encaissé',
      description: 'Cumul des encaissements, pour suivre les paiements partiels',
      icon: 'IconCashBanknote',
      isNullable: true,
    },
    {
      universalIdentifier: 'b11a0100-0001-4000-8000-00000000000e',
      type: FieldType.RICH_TEXT,
      name: 'notes',
      label: 'Notes et mentions',
      icon: 'IconFileText',
      isNullable: true,
    },
    {
      universalIdentifier: 'b11a0100-0001-4000-8000-00000000000f',
      type: FieldType.FILES,
      name: 'documents',
      label: 'Pièces jointes',
      icon: 'IconPaperclip',
      isNullable: true,
    },
    {
      universalIdentifier: 'b11a0100-0001-4000-8000-000000000010',
      type: FieldType.BOOLEAN,
      name: 'isRecurring',
      label: 'Récurrente',
      icon: 'IconRepeat',
      defaultValue: false,
    },
    {
      universalIdentifier: 'b11a0100-0001-4000-8000-000000000011',
      type: FieldType.SELECT,
      name: 'recurrence',
      label: 'Périodicité',
      icon: 'IconRepeat',
      isNullable: true,
      options: recurrenceOptions('01'),
    },
    {
      universalIdentifier: 'b11a0100-0001-4000-8000-000000000012',
      type: FieldType.DATE_TIME,
      name: 'nextIssueDate',
      label: 'Prochaine émission',
      icon: 'IconCalendarPlus',
      isNullable: true,
    },
    {
      universalIdentifier: 'b11a0100-0001-4000-8000-000000000013',
      type: FieldType.NUMBER,
      name: 'remindersSentCount',
      label: 'Relances envoyées',
      icon: 'IconBellRinging',
      defaultValue: 0,
    },
    {
      universalIdentifier: 'b11a0100-0001-4000-8000-000000000014',
      type: FieldType.DATE_TIME,
      name: 'lastReminderAt',
      label: 'Dernière relance',
      icon: 'IconBell',
      isNullable: true,
    },
    {
      universalIdentifier: 'b11a0100-0001-4000-8000-000000000015',
      type: FieldType.RAW_JSON,
      name: 'vatSummary',
      label: 'Détail de TVA par taux',
      description:
        'Ventilation calculée à l’enregistrement : un contrôle lit ce détail, pas le total.',
      icon: 'IconTable',
      isNullable: true,
    },
    {
      universalIdentifier: RELATION_IDS.invoiceClient,
      type: FieldType.RELATION,
      name: 'client',
      label: 'Client',
      icon: 'IconBuildingSkyscraper',
      relationTargetObjectMetadataUniversalIdentifier:
        STANDARD_OBJECT_UNIVERSAL_IDENTIFIERS.company.universalIdentifier,
      relationTargetFieldMetadataUniversalIdentifier:
        RELATION_IDS.companyInvoices,
      universalSettings: {
        ...manyToOne('clientId'),
        onDelete: OnDeleteAction.SET_NULL,
      },
    },
    {
      universalIdentifier: RELATION_IDS.invoiceOpportunity,
      type: FieldType.RELATION,
      name: 'opportunity',
      label: 'Opportunité',
      icon: 'IconTargetArrow',
      relationTargetObjectMetadataUniversalIdentifier:
        STANDARD_OBJECT_UNIVERSAL_IDENTIFIERS.opportunity.universalIdentifier,
      relationTargetFieldMetadataUniversalIdentifier:
        RELATION_IDS.opportunityInvoices,
      universalSettings: {
        ...manyToOne('opportunityId'),
        onDelete: OnDeleteAction.SET_NULL,
      },
    },
    {
      universalIdentifier: RELATION_IDS.invoiceLines,
      type: FieldType.RELATION,
      name: 'lines',
      label: 'Lignes',
      icon: 'IconListNumbers',
      relationTargetObjectMetadataUniversalIdentifier: OBJECT_IDS.invoiceLine,
      relationTargetFieldMetadataUniversalIdentifier:
        RELATION_IDS.invoiceLineInvoice,
      universalSettings: oneToMany,
    },
    {
      universalIdentifier: RELATION_IDS.invoiceFinanceEntries,
      type: FieldType.RELATION,
      name: 'financeEntries',
      label: 'Encaissements',
      icon: 'IconArrowsExchange',
      relationTargetObjectMetadataUniversalIdentifier: OBJECT_IDS.financeEntry,
      relationTargetFieldMetadataUniversalIdentifier:
        RELATION_IDS.financeEntryInvoice,
      universalSettings: oneToMany,
    },
    {
      universalIdentifier: RELATION_IDS.invoiceLedgerEntries,
      type: FieldType.RELATION,
      name: 'ledgerEntries',
      label: 'Écritures du livre',
      icon: 'IconBook',
      relationTargetObjectMetadataUniversalIdentifier: OBJECT_IDS.bookEntry,
      relationTargetFieldMetadataUniversalIdentifier:
        RELATION_IDS.bookEntryInvoice,
      universalSettings: oneToMany,
    },
    {
      universalIdentifier: RELATION_IDS.invoiceSourceQuotes,
      type: FieldType.RELATION,
      name: 'sourceQuotes',
      label: 'Devis à l’origine',
      description:
        'Trace de conversion : un devis transformé garde le lien vers sa facture.',
      icon: 'IconFileDescription',
      relationTargetObjectMetadataUniversalIdentifier: OBJECT_IDS.quote,
      relationTargetFieldMetadataUniversalIdentifier:
        RELATION_IDS.quoteConvertedInvoice,
      universalSettings: oneToMany,
    },
  ],
});
