import {
  ForbiddenException,
  UseFilters,
  UseGuards,
  UsePipes,
} from '@nestjs/common';
import { Args, Mutation, Query } from '@nestjs/graphql';

import { isDefined } from 'twenty-shared/utils';

import { MetadataResolver } from 'src/engine/api/graphql/graphql-config/decorators/metadata-resolver.decorator';
import { AuthGraphqlApiExceptionFilter } from 'src/engine/core-modules/auth/filters/auth-graphql-api-exception.filter';
import { ResolverValidationPipe } from 'src/engine/core-modules/graphql/pipes/resolver-validation.pipe';
import { WorkspaceEntity } from 'src/engine/core-modules/workspace/workspace.entity';
import { AuthWorkspaceMemberId } from 'src/engine/decorators/auth/auth-workspace-member-id.decorator';
import { AuthWorkspace } from 'src/engine/decorators/auth/auth-workspace.decorator';
import { CustomPermissionGuard } from 'src/engine/guards/custom-permission.guard';
import { WorkspaceAuthGuard } from 'src/engine/guards/workspace-auth.guard';
import { ChatMessageConnectionDTO } from 'src/modules/chat/dtos/chat-message-connection.dto';
import { ChatMessagesArgs } from 'src/modules/chat/dtos/chat-messages.args';
import { ChatTypingIndicatorDTO } from 'src/modules/chat/dtos/chat-typing-indicator.dto';
import { ChatUnreadCountDTO } from 'src/modules/chat/dtos/chat-unread-count.dto';
import { SendChatTypingInput } from 'src/modules/chat/dtos/send-chat-typing.input';
import { ChatMessageService } from 'src/modules/chat/services/chat-message.service';
import { ChatTypingService } from 'src/modules/chat/services/chat-typing.service';
import { ChatUnreadCountService } from 'src/modules/chat/services/chat-unread-count.service';

// Chat GraphQL beyond metadata CRUD. Channels/members/messages/reactions and
// read cursors are app-owned metadata objects, so their CRUD + cursor
// pagination are generated by the metadata engine. This resolver adds the two
// things metadata cannot express: a newest-first message connection scoped to
// one channel, and ephemeral typing events.
@MetadataResolver()
@UsePipes(ResolverValidationPipe)
@UseFilters(AuthGraphqlApiExceptionFilter)
@UseGuards(WorkspaceAuthGuard, CustomPermissionGuard)
export class ChatResolver {
  constructor(
    private readonly chatMessageService: ChatMessageService,
    private readonly chatTypingService: ChatTypingService,
    private readonly chatUnreadCountService: ChatUnreadCountService,
  ) {}

  @Query(() => ChatMessageConnectionDTO)
  async chatMessages(
    @AuthWorkspace() workspace: WorkspaceEntity,
    @Args() { channelId, limit, after }: ChatMessagesArgs,
  ): Promise<ChatMessageConnectionDTO> {
    return this.chatMessageService.listChannelMessages({
      workspaceId: workspace.id,
      channelId,
      limit,
      after,
    });
  }

  @Query(() => [ChatUnreadCountDTO])
  async chatUnreadCounts(
    @AuthWorkspace() workspace: WorkspaceEntity,
    @AuthWorkspaceMemberId() workspaceMemberId: string | undefined,
  ): Promise<ChatUnreadCountDTO[]> {
    if (!isDefined(workspaceMemberId)) {
      throw new ForbiddenException(
        'Unread counts require an authenticated workspace member',
      );
    }

    return this.chatUnreadCountService.listUnreadCounts({
      workspaceId: workspace.id,
      workspaceMemberId,
    });
  }

  @Mutation(() => ChatTypingIndicatorDTO)
  async sendChatTypingIndicator(
    @AuthWorkspace() workspace: WorkspaceEntity,
    @AuthWorkspaceMemberId() workspaceMemberId: string | undefined,
    @Args('input') input: SendChatTypingInput,
  ): Promise<ChatTypingIndicatorDTO> {
    if (!isDefined(workspaceMemberId)) {
      throw new ForbiddenException(
        'Typing indicators require an authenticated workspace member',
      );
    }

    return this.chatTypingService.publishTypingIndicator({
      workspaceId: workspace.id,
      channelId: input.channelId,
      workspaceMemberId,
      isTyping: input.isTyping,
    });
  }
}
